### PR TITLE
[Fix] Update dynamic table metadata queryies to take into account new object type.

### LINKED ISSUE #934: [Regression] Snowflake is now populating a value for the relation type on dynamic tables, which is not properly reflected in the metadata queries
### Is this a regression in a recent version of dbt-snowflake?

- [X] I believe this is a regression in dbt-snowflake functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Querying the relation type on a dynamic table produces "BASE TABLE". This used to be empty, and was coalesced to a value unique to dynamic tables.

### Expected/Previous Behavior

Querying the relation type on a dynamic table should produce "DYNAMIC TABLE".

### Steps To Reproduce

- create a dynamic table
- query the relation type, or, do anything dependent on the relation type
- note that you get behavior suggesting it's a traditional table

### Relevant log output

_No response_

### Environment

```markdown
- OS:
- Python:
- dbt-core (working version):
- dbt-snowflake (working version):
- dbt-core (regression version):
- dbt-snowflake (regression version):
```

### Additional Context

We need to update the metadata query. Because it looks like the value selected matches that of a traditional table, we'll need to look for another field to differentiate the two, such as an update frequency, or the presence in a metadata table that only contains dynamic tables.

### PR DESCRIPTION
**Pull request by McKnight-42**
resolves #934 
[docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) dbt-labs/docs.getdbt.com/#

### Problem
Snowflake gave dynamic tables a object type of `BASE TABLE` when it was null now we need to modify our SQL queries to build out the tables based.

### Checklist

- [ ] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

File: dbt/include/snowflake/macros/catalog.sql [hunk 1]
```diff
@@ -41,7 +41,10 @@
         table_catalog as "table_database",
         table_schema as "table_schema",
         table_name as "table_name",
-        coalesce(table_type, 'DYNAMIC TABLE') as "table_type",
+        case
+            when target_lag not null and table_type = 'BASE TABLE' THEN 'DYNAMIC TABLE'
+            else coalesce(table_type, 'BASE TABLE')
```
Comment (mikealfare) [inline dbt/include/snowflake/macros/catalog.sql:46]: I would get rid of the `coalesce` since we should no longer need it. So just `else table_type`.

**Review by mikealfare — APPROVED** [review]
