### PR TITLE
Normalize is_iceberg Field for Consistency in Snowflake with QUOTED_IDENTIFIERS_IGNORE_CASE

### LINKED ISSUE #1227: [Bug] Setting the enable_iceberg_materializations flag to True on a dbt project that is connected to a Snowflake account with QUOTED_IDENTIFIERS_IGNORE_CASE = true results in error tuple.index(x): x not in tuple
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Currently in dbt Cloud in order to create Iceberg tables, you must implement a [behavior flag](https://docs.getdbt.com/reference/global-configs/behavior-changes) due to performance impact related to using Iceberg tables. Snowflake does not support is_iceberg on the Show Objects query, which dbt depends on for metadata. To use Iceberg, you need to set the enable_iceberg_materializations flag to True in your dbt_project.yml:
```
flags:
  enable_iceberg_materializations: True
```

However, if the Snowflake account that is connected to your dbt Cloud project has the flag `QUOTED_IDENTIFIERS_IGNORE_CASE` set to `True`, this results in the following error:
```
tuple.index(x): x not in tuple
```

This appears to occur when we run the following query:
```
select all_objects.*, is_iceberg as "is_iceberg"
      from table(result_scan(last_query_id(-1))) all_objects
      left join INFORMATION_SCHEMA.tables as all_tables
        on all_tables.table_name = all_objects."name"
        and all_tables.table_schema = all_objects."schema_name"
        and all_tables.table_catalog = all_objects."database_name"
```

### Expected Behavior

dbt should be able to handle quoting/casing while this flag is set to True in Snowflake.

### Steps To Reproduce

1. Set `QUOTED_IDENTIFIERS_IGNORE_CASE` to `True` in Snowflake:

```
ALTER ACCOUNT SET QUOTED_IDENTIFIERS_IGNORE_CASE = TRUE;
```

2. Set flag `enable_iceberg_materializations` to `True` in `dbt_project.yml` file:
```
flags:
  enable_iceberg_materializations: True
```
3. Try to run anything in your dbt Cloud project (IDE):
```
dbt build --select some_model
```

From the debug logs:
```
02:50:27 Running dbt...
02:50:27 running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': '/usr/src/dbt-server-shared/working_dir/b580a02e-eff8-4c74-bca7-04bc720476ad', 'profiles_dir': '/usr/src/dbt-server-shared/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'json', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt -A dbt_worker.app worker --loglevel=DEBUG --concurrency=2 --max-memory-per-child=500000', 'send_anonymous_usage_stats': 'True'}
02:50:27 Discovered Exposures:
[]
02:50:27 Registered adapter: snowflake=1.9.0-post10+78f86674bc726000686a484c4d2f0e2f9d350ed1
02:50:27 checksum: b27b306c093216d1116c3927e0401dd24e00d277a1f26f4c8f3a5342a1df6db2, vars: {}, profile: user, target: , version: 2024.10.28+996c6a8
02:50:27 Observability Metric: msgpack_manifest_bytes=481202.0
02:50:27 Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
02:50:27 Partial parsing enabled, no changes found, skipping parsing
02:50:27 [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.my_new_project.example
02:50:27 Observability Metric: path_count=143.0
02:50:27 Observability Metric: parsed_path_count=0.0
02:50:27 Observability Metric: read_files_elapsed=0.012346978299319744
02:50:27 Observability Metric: load_macros_elapsed=0.0
02:50:27 Observability Metric: parse_project_elapsed=0.0
02:50:27 Observability Metric: patch_sources_elapsed=0.0
02:50:27 Observability Metric: process_manifest_elapsed=0.0
02:50:27 Observability Metric: load_all_elapsed=0.029497478157281876
02:50:27 Observability Metric: is_partial_parse_enabled=1.0
02:50:27 Found 2 models, 468 macros
02:50:27 
02:50:27 Concurrency: 6 threads (target='default')
02:50:27 
02:50:27 Acquiring new snowflake connection 'master'
02:50:27 Acquiring new snowflake connection 'list_ANALYTICS'
02:50:27 Using snowflake connection "list_ANALYTICS"
02:50:27 On list_ANALYTICS: /* {"app": "dbt", "dbt_version": "2024.10.28+996c6a8", "profile_name": "user", "target_name": "default", "connection_name": "list_ANALYTICS"} */
show terse schemas in database ANALYTICS
    limit 10000
02:50:27 Opening a new connection, currently in state init
02:50:27 SQL status: SUCCESS 2 in 0.659 seconds
02:50:27 Re-using an available connection from the pool (formerly list_ANALYTICS, now list_ANALYTICS_dev_tonayya)
02:50:27 Using snowflake connection "list_ANALYTICS_dev_tonayya"
02:50:27 On list_ANALYTICS_dev_tonayya: /* {"app": "dbt", "dbt_version": "2024.10.28+996c6a8", "profile_name": "user", "target_name": "default", "connection_name": "list_ANALYTICS_dev_tonayya"} */
show objects in ANALYTICS.dev_tonayya limit 10000;
02:50:27 SQL status: SUCCESS 3 in 0.163 seconds
02:50:27 Using snowflake connection "list_ANALYTICS_dev_tonayya"
02:50:27 On list_ANALYTICS_dev_tonayya: /* {"app": "dbt", "dbt_version": "2024.10.28+996c6a8", "profile_name": "user", "target_name": "default", "connection_name": "list_ANALYTICS_dev_tonayya"} */
select all_objects.*, is_iceberg as "is_iceberg"
      from table(result_scan(last_query_id(-1))) all_objects
      left join INFORMATION_SCHEMA.tables as all_tables
        on all_tables.table_name = all_objects."name"
        and all_tables.table_schema = all_objects."schema_name"
        and all_tables.table_catalog = all_objects."database_name"
02:50:29 SQL status: SUCCESS 3 in 1.433 seconds
02:50:29 Connection 'master' was properly closed.
02:50:29 Connection 'list_ANALYTICS_dev_tonayya' was left open.
02:50:29 On list_ANALYTICS_dev_tonayya: Close
02:50:29 
02:50:29 Finished running  in 0 hours 0 minutes and 2.46 seconds (2.46s).
02:50:29 Encountered an error:
tuple.index(x): x not in tuple
02:50:29 Traceback (most recent call last):
  File "/venv/dbt-996c6a882dc72d24e24395693ebca65139cb1575/lib/python3.11/site-packages/dbt/cli/requires.py", line 222, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-996c6a882dc72d24e24395693ebca65139cb1575/lib/python3.11/site-packages/dbt/cli/requires.py", line 132, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-996c6a882dc72d24e24395693ebca65139cb1575/lib/python3.11/site-packages/dbt/cli/requires.py", line 334, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-996c6a882dc72d24e24395693ebca65139cb1575/lib/python3.11/site-packages/dbt/cli/requires.py", line 361, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-996c6a882dc72d24e24395693ebca65139cb1575/lib/python3.11/site-packages/dbt/cli/requires.py", line 413, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-996c6a882dc72d24e24395693ebca65139cb1575/lib/python3.11/site-packages/dbt/cli/requires.py", line 435, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-996c6a882dc72d24e24395693ebca65139cb1575/lib/python3.11/site-packages/dbt/cli/main.py", line 206, in build
    results = task.run()
              ^^^^^^^^^^
  File "/venv/dbt-996c6a882dc72d24e24395693ebca65139cb1575/lib/python3.11/site-packages/dbt/task/runnable.py", line 608, in run
    result = self.execute_with_hooks(selected_uids)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-996c6a882dc72d24e24395693ebca65139cb1575/lib/python3.11/site-packages/dbt/task/runnable.py", line 546, in execute_with_hooks
    before_run_status = self.before_run(adapter, selected_uids)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-996c6a882dc72d24e24395693ebca65139cb1575/lib/python3.11/site-packages/dbt/task/run.py", line 756, in before_run
    self.populate_adapter_cache(adapter, required_schemas)
  File "/venv/dbt-996c6a882dc72d24e24395693ebca65139cb1575/lib/python3.11/site-packages/dbt/task/runnable.py", line 505, in populate_adapter_cache
    adapter.set_relations_cache(cachable_nodes)
  File "/venv/dbt-996c6a882dc72d24e24395693ebca65139cb1575/lib/python3.11/site-packages/dbt/adapters/base/impl.py", line 552, in set_relations_cache
    self._relations_cache_for_schemas(relation_configs, required_schemas)
  File "/venv/dbt-996c6a882dc72d24e24395693ebca65139cb1575/lib/python3.11/site-packages/dbt/adapters/base/impl.py", line 528, in _relations_cache_for_schemas
    for relation in future.result():
                    ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-996c6a882dc72d24e24395693ebca65139cb1575/lib/python3.11/site-packages/ddtrace/contrib/futures/threading.py", line 44, in _wrap_execution
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-996c6a882dc72d24e24395693ebca65139cb1575/lib/python3.11/site-packages/dbt_common/utils/executor.py", line 16, in connected
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-996c6a882dc72d24e24395693ebca65139cb1575/lib/python3.11/site-packages/dbt/adapters/snowflake/impl.py", line 266, in list_relations_without_caching
    return [self._parse_list_relations_result(obj) for obj in schema_objects.select(columns)]
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-996c6a882dc72d24e24395693ebca65139cb1575/lib/python3.11/site-packages/agate/table/select.py", line 18, in select
    indexes = tuple(self._column_names.index(k) for k in key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-996c6a882dc72d24e24395693ebca65139cb1575/lib/python3.11/site-packages/agate/table/select.py", line 18, in <genexpr>
    indexes = tuple(self._column_names.index(k) for k in key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: tuple.index(x): x not in tuple

02:50:29 Resource report: {"command_name": "build", "command_wall_clock_time": 2.520353, "process_user_time": 5.677027, "process_kernel_time": 1.493451, "process_mem_max_rss": "322364", "process_in_blocks": "264", "process_out_blocks": "32088", "command_success": false}
02:50:29 Observability Metric: command_success=0.0
02:50:29 Observability Metric: command_wall_clock_time=2.520353078842163
02:50:29 Observability Metric: process_user_time=5.677027225494385
02:50:29 Observability Metric: process_kernel_time=1.4934509992599487
02:50:29 Observability Metric: process_mem_max_rss=322364.0
02:50:29 Command `cli build` failed at 02:50:29.523857 after 2.52 seconds
```

### Relevant log output

_No response_

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-snowflake:
```

### Additional Context

This is fairly similar to the bug reported [here](https://github.com/dbt-labs/dbt-snowflake/issues/1160)

### PR DESCRIPTION
**Pull request by VersusFacit**
resolves #1227 

### Problem

In Snowflake, the `QUOTED_IDENTIFIERS_IGNORE_CASE` setting influences column names created by users, such as `is_iceberg`. However, this setting does not affect the column values returned by Snowflake’s `SHOW OBJECTS` query, creating inconsistency in how the `is_iceberg` field is referenced across different parts of the code.

When `QUOTED_IDENTIFIERS_IGNORE_CASE` is enabled, the `is_iceberg` column may appear in uppercase (`IS_ICEBERG`) in our homemade `SHOW OBJECTS` query, causing potential misalignment with the system table's always lowercase column names. This mismatch requires normalization to consistently refer to `is_iceberg` as a lowercase field name across Snowflake queries and Python processing, especially when working with adapters that handle Iceberg materializations.

### Solution

Take 2: Removing quoting from the problem entirely and prove by hand that quoting in this metadata query doesn't matter one way or another.

I did so by hand and verified the test fails before the two fix lines are inserted.

just for fun, I did this with tdd: reproduce the failure/error, add the fix, go green!~~

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

File: dbt/include/snowflake/macros/adapters.sql [hunk 1]
```diff
@@ -145,9 +145,12 @@
...
 
     {# -- Gated for performance reason. If you don't want Iceberg, you shouldn't pay the
-       -- latency penalty. #}
+       -- latency penalty.
+       --
+       -- Note: The capitalization of is_iceberg is handled in Python due to
+       -- unpredictable quoting behavior based on QUOTED_IDENTIFIERS_IGNORE_CASE. #}
     {% if adapter.behavior.enable_iceberg_materializations.no_warn %}
-      select all_objects.*, is_iceberg as "is_iceberg"
+      select all_objects.*, is_iceberg as {{ adapter.quote('is_iceberg') }}
```
Comment (VersusFacit) [inline dbt/include/snowflake/macros/adapters.sql:153]: This is more code style than anything

File: dbt/adapters/snowflake/impl.py [hunk 2]
```diff
@@ -263,6 +263,15 @@ def list_relations_without_caching(
...
         if self.behavior.enable_iceberg_materializations.no_warn:
+            # The QUOTED_IDENTIFIERS_IGNORE_CASE setting impacts column names like
+            # is_iceberg which is created by dbt, but it does not affect the case
+            # of column values in Snowflake's SHOW OBJECTS query! This normalization
+            # step ensures consistent scanning of the is_iceberg column as a
+            # lowercase name, treating it as if it were a system-provided field.
+            #
+            # This along with the behavior flag in general may be removed when
+            # is_iceberg comes on show objects.
+            schema_objects = schema_objects.rename(column_names={"IS_ICEBERG": "is_iceberg"})
```
Comment (mikealfare) [inline dbt/adapters/snowflake/impl.py:274]: As a sanity check, did you confirm that the new test below fails when this line is commented out?

**Review by mikealfare — DISMISSED** [review]
One sanity check, other wise it looks good. The failing CI is due to an expired token that we need to update.

File: dbt/adapters/snowflake/impl.py (hunk 2 above)
Comment (VersusFacit) [reply dbt/adapters/snowflake/impl.py:274]: Yep I wrote this in the description of the PR. I explicitly reproduced, got the fail on the test, then added this and watched it go green.

Comment (VersusFacit) [reply dbt/adapters/snowflake/impl.py:274]: Oh one added wrinkle is I temporarily set the QUOTED_IDENTIFIERS_IGNORE_CASE on in the macro. I didn't capture that in the test. Let me rework for that. Glad you said something as this test is missing a configuration!

Comment (VersusFacit) [reply dbt/adapters/snowflake/impl.py:274]: With the new test I have properly verified removing this line reproduces the error in the test itself.

File: dbt/include/snowflake/macros/adapters.sql [hunk 3]
```diff
@@ -134,20 +134,29 @@
...
 {% endmacro %}
 
-{% macro snowflake__list_relations_without_caching(schema_relation, max_iter=10, max_results_per_iter=10000) %}
+{% macro snowflake__list_relations_without_caching(schema_relation, max_iter=10, max_results_per_iter=10000, query_pre_hook=None) %}
+  {# -- Use query_pre_hook for optional configurations prior to fetching relations. For sake of
+     -- consistent use, place ;s in the query_pre_hook definition, not this macro. #}
 
   {%- set max_total_results = max_results_per_iter * max_iter -%}
   {%- set sql -%}
+    {% if query_pre_hook %}
```
Comment (VersusFacit) [inline dbt/include/snowflake/macros/adapters.sql:143]: this is a conservative move because I think we could just not have the guard, but it's very easy to cause iterable unpack errors from empty queries (only `;`) and this helps avoid that.

File: dbt/include/snowflake/macros/adapters.sql [hunk 4]
```diff
@@ -134,20 +134,29 @@
 
 {% endmacro %}
 
-{% macro snowflake__list_relations_without_caching(schema_relation, max_iter=10, max_results_per_iter=10000) %}
+{% macro snowflake__list_relations_without_caching(schema_relation, max_iter=10, max_results_per_iter=10000, query_pre_hook=None) %}
```
Comment (VersusFacit) [inline dbt/include/snowflake/macros/adapters.sql:137]: I know this is QUITE the move to make but I couldn't think of another way to test for when this flag is set for a test. I think this will come in handy when we do other `QUOTED_IDENTIFIERS_IGNORE_CASE`-related matters.

I stand by this as the best move I can make but I recognize it may not be enough per se.

**Comment by adrianburusdbt** [comment]
@VersusFacit, there are a few other scenarios we need to consider as well, like this one: https://github.com/dbt-labs/dbt-core/issues/4422
The way we handle `QUOTED_IDENTIFIERS_IGNORE_CASE` is again the culprit, so I think we should fix this issue throughout the adapter, not just for `is_iceberg`

File: dbt/include/snowflake/macros/adapters.sql [hunk 5]
```diff
@@ -147,7 +149,7 @@
     {# -- Gated for performance reason. If you don't want Iceberg, you shouldn't pay the
        -- latency penalty. #}
     {% if adapter.behavior.enable_iceberg_materializations.no_warn %}
-      select all_objects.*, is_iceberg as "is_iceberg"
+      select all_objects.*, is_iceberg
```
Comment (VersusFacit) [inline dbt/include/snowflake/macros/adapters.sql:152]: I tested in by manually place `QUOTED_IDENTIFIERS_IGNORE_CASE = true` and `QUOTED_IDENTIFIERS_IGNORE_CASE = false` and then verifying it didn't matter. This is a more predictable way to handle metadata query column names.

File: dbt/include/snowflake/macros/adapters.sql (hunk 4 above)
Comment (VersusFacit) [reply dbt/include/snowflake/macros/adapters.sql]: We found a much better way forward by rethinking the underlying logic for metadata columns :)

File: dbt/include/snowflake/macros/adapters.sql [hunk 6]
```diff
@@ -135,6 +135,8 @@
 {% endmacro %}
 
 {% macro snowflake__list_relations_without_caching(schema_relation, max_iter=10, max_results_per_iter=10000) %}
+  {# -- Use query_pre_hook for optional configurations prior to fetching relations. For sake of
```
Comment (mikealfare) [inline dbt/include/snowflake/macros/adapters.sql:138]: I think this comment is now outdated.

File: tests/functional/adapter/list_relations_tests/test_show_objects.py [hunk 7]
```diff
@@ -87,3 +103,21 @@ def test_list_relations_without_caching(self, project):
...
+    @pytest.fixture(scope="class")
+    def project_config_update(self):
+        return {"flags": {"enable_iceberg_materializations": True}}
+
+    @pytest.fixture(scope="class")
+    def models(self):
+        return {"my_model.sql": _MODEL_ICEBERG}
+
+    def test_quoting_ignore_flag_doesnt_break_iceberg_metadata(self, project):
+        """We inject the QUOTED_IDENTIFIERS_IGNORE_CASE into the underlying query that fetches
```
Comment (mikealfare) [inline tests/functional/adapter/list_relations_tests/test_show_objects.py:118]: When creating a test case for a specific bug, I like linking to the originating issue in the docstring. While git blame will do some of that for you, it makes it very clear why we're testing this particular functionality.

**Review by mikealfare — APPROVED** [review]
Two comments suggesting docstring updates, but these are non-blocking.

File: dbt/include/snowflake/macros/adapters.sql (hunk 6 above)
Comment (VersusFacit) [reply dbt/include/snowflake/macros/adapters.sql:138]: Oop, patched that wrong. Thanks!

File: tests/functional/adapter/list_relations_tests/test_show_objects.py (hunk 7 above)
Comment (VersusFacit) [reply tests/functional/adapter/list_relations_tests/test_show_objects.py:118]: Can do!
