### PR TITLE
Use timestamp_tz type in microbatch `delete` DDL

### LINKED ISSUE #364: [Bug] Microbatch: Using backfill results in inefficient delete statements (Snowflake adapter)
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When running a model configured with the new microbatch strategy to backfill older dates with some previously loaded data, dbt produces a delete statement to remove records for the periods being backfilled. The delete statement produces a SQL statement for the Snowflake adapter that results in a cartesian product causing the statement to run for much longer than is necessary.

### Expected Behavior

Existing records should be deleted efficiently without a cartesian join.

SQL to delete existing records should not be generated with a "using" clause with the temp table. (see steps to reproduce)

### Steps To Reproduce

1. using dbt-snowflake adapter version 1.9.0-b1 and dbt-core version 1.9.0-b4
2. Create a model using the microbatch incremental strategy (
3. Run the model to load some data.
`dbt run -s <model>`
4. Run the model again as a backfill where the time range overlaps with data that was prevsiously loaded
`dbt run -s <model> --event-time-start "<start timestamp>" --event-time-end "<end timestamp>"`
5. After creating a temp table for the first batch, a SQL statement to delete existing records is run to remove existing records from the target before inserting the new records in the temp table. This SQL is written such that a cartesian join is created resulting in a long-running query.

Example model config:
```sql
{{
  config(
    materialized='incremental',
    incremental_strategy='microbatch',
    event_time='content_recognition_start_timestamp',
    begin='2024-01-01',
    batch_size='day',
    )
}}
```

Example dbt commands:
```shell
dbt run -s content
dbt run -s content --event-time-start "2024-11-20" --event-time-end "2024-11-25"
```

dbt generated SQL to delete existing records:
```sql
delete from CURATED_CLONE.inscape.content DBT_INTERNAL_TARGET
    using CURATED_CLONE.inscape.content__dbt_tmp
    where (
    DBT_INTERNAL_TARGET.content_recognition_start_timestamp >= TIMESTAMP '2023-11-24 00:00:00+00:00'
    and DBT_INTERNAL_TARGET.content_recognition_start_timestamp < TIMESTAMP '2023-11-25 00:00:00+00:00'    
    );
```

The using with the temp table is unnecessary and causes a cartesian join.

### Relevant log output

```shell
============================== 11:18:47.298457 | cdd2a509-9a0f-463d-b3e1-54879743f040 ==============================
[0m11:18:47.298457 [info ] [MainThread]: Running with dbt=1.9.0-b4
[0m11:18:47.299457 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'C:\\repos\\hmi_dbt_lib\\logs', 'profiles_dir': 'C:\\Users\\BFranklin\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run -s content --event-time-start 2023-11-24 --event-time-end 2023-11-25 --target sso', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:18:47.628432 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'cdd2a509-9a0f-463d-b3e1-54879743f040', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000233BE7DF8F0>]}
[0m11:18:47.673431 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'cdd2a509-9a0f-463d-b3e1-54879743f040', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000233BF4FCA40>]}
[0m11:18:47.673431 [info ] [MainThread]: Registered adapter: snowflake=1.9.0-b1
[0m11:18:47.883198 [debug] [MainThread]: checksum: 0a22b8766ab724bfaebfe4fc1d2ad384caab58113fa005bc2edb50f306de7ed8, vars: {}, profile: , target: sso, version: 1.9.0b4
[0m11:18:47.982669 [info ] [MainThread]: Unable to do partial parsing because of a version mismatch
[0m11:18:47.982669 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'cdd2a509-9a0f-463d-b3e1-54879743f040', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000233BE7AB7A0>]}
[0m11:18:51.581484 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.hmi_dbt_lib.processed
[0m11:18:51.591511 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'cdd2a509-9a0f-463d-b3e1-54879743f040', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000233C0FC7020>]}
[0m11:18:51.710445 [debug] [MainThread]: Wrote artifact WritableManifest to C:\repos\hmi_dbt_lib\target\manifest.json
[0m11:18:51.714445 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\repos\hmi_dbt_lib\target\semantic_manifest.json
[0m11:18:51.745931 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'cdd2a509-9a0f-463d-b3e1-54879743f040', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000233C0E0E7B0>]}
[0m11:18:51.746931 [info ] [MainThread]: Found 20 models, 40 data tests, 24 sources, 1351 macros
[0m11:18:51.747932 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'cdd2a509-9a0f-463d-b3e1-54879743f040', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000233C1042210>]}
[0m11:18:51.749940 [info ] [MainThread]: 
[0m11:18:51.749940 [info ] [MainThread]: Concurrency: 2 threads (target='sso')
[0m11:18:51.751089 [info ] [MainThread]: 
[0m11:18:51.752127 [debug] [MainThread]: Acquiring new snowflake connection 'master'
[0m11:18:51.753175 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_HMI_CURATED_CLONE_PROD_NS1_656'
[0m11:18:51.821249 [debug] [ThreadPool]: Using snowflake connection "list_HMI_CURATED_CLONE_PROD_NS1_656"
[0m11:18:51.822331 [debug] [ThreadPool]: On list_HMI_CURATED_CLONE_PROD_NS1_656: /* {"app": "dbt", "dbt_version": "1.9.0b4", "profile_name": "hmi_dbt_lib", "target_name": "sso", "connection_name": "list_HMI_CURATED_CLONE_PROD_NS1_656"} */
show terse schemas in database HMI_CURATED_CLONE_PROD_NS1_656
    limit 10000
[0m11:18:51.822331 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m11:18:55.494947 [debug] [ThreadPool]: SQL status: SUCCESS 21 in 3.673 seconds
[0m11:18:55.499987 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_HMI_CURATED_CLONE_PROD_NS1_656_orkin'
[0m11:18:55.507128 [debug] [ThreadPool]: Using snowflake connection "list_HMI_CURATED_CLONE_PROD_NS1_656_orkin"
[0m11:18:55.508119 [debug] [ThreadPool]: Acquiring new snowflake connection 'list_HMI_LANDED_CLONE_PROD_NS_725_orkin'
[0m11:18:55.508119 [debug] [ThreadPool]: On list_HMI_CURATED_CLONE_PROD_NS1_656_orkin: /* {"app": "dbt", "dbt_version": "1.9.0b4", "profile_name": "hmi_dbt_lib", "target_name": "sso", "connection_name": "list_HMI_CURATED_CLONE_PROD_NS1_656_orkin"} */
show objects in HMI_CURATED_CLONE_PROD_NS1_656.orkin limit 10000;
[0m11:18:55.511017 [debug] [ThreadPool]: Using snowflake connection "list_HMI_LANDED_CLONE_PROD_NS_725_orkin"
[0m11:18:55.512039 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m11:18:55.512039 [debug] [ThreadPool]: On list_HMI_LANDED_CLONE_PROD_NS_725_orkin: /* {"app": "dbt", "dbt_version": "1.9.0b4", "profile_name": "hmi_dbt_lib", "target_name": "sso", "connection_name": "list_HMI_LANDED_CLONE_PROD_NS_725_orkin"} */
show objects in HMI_LANDED_CLONE_PROD_NS_725.orkin limit 10000;
[0m11:18:55.512039 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m11:18:59.077076 [debug] [ThreadPool]: SQL status: SUCCESS 3 in 3.565 seconds
[0m11:18:59.079075 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_HMI_LANDED_CLONE_PROD_NS_725_orkin, now list_hmi_dev_sandbox)
[0m11:18:59.081656 [debug] [ThreadPool]: Using snowflake connection "list_hmi_dev_sandbox"
[0m11:18:59.082661 [debug] [ThreadPool]: On list_hmi_dev_sandbox: /* {"app": "dbt", "dbt_version": "1.9.0b4", "profile_name": "hmi_dbt_lib", "target_name": "sso", "connection_name": "list_hmi_dev_sandbox"} */
show objects in hmi_dev.sandbox limit 10000;
[0m11:18:59.219623 [debug] [ThreadPool]: SQL status: SUCCESS 8 in 0.136 seconds
[0m11:18:59.220703 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_hmi_dev_sandbox, now list_HMI_CURATED_CLONE_PROD_NS1_656_inscape)
[0m11:18:59.222631 [debug] [ThreadPool]: Using snowflake connection "list_HMI_CURATED_CLONE_PROD_NS1_656_inscape"
[0m11:18:59.223692 [debug] [ThreadPool]: On list_HMI_CURATED_CLONE_PROD_NS1_656_inscape: /* {"app": "dbt", "dbt_version": "1.9.0b4", "profile_name": "hmi_dbt_lib", "target_name": "sso", "connection_name": "list_HMI_CURATED_CLONE_PROD_NS1_656_inscape"} */
show objects in HMI_CURATED_CLONE_PROD_NS1_656.inscape limit 10000;
[0m11:18:59.296905 [debug] [ThreadPool]: SQL status: SUCCESS 3 in 3.785 seconds
[0m11:18:59.338385 [debug] [ThreadPool]: SQL status: SUCCESS 13 in 0.115 seconds
[0m11:18:59.342383 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'cdd2a509-9a0f-463d-b3e1-54879743f040', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000233C1678CE0>]}
[0m11:18:59.346079 [debug] [Thread-1 (]: Began running node model.hmi_dbt_lib.content
[0m11:18:59.347151 [info ] [Thread-1 (]: 1 of 1 START sql microbatch model HMI_CURATED_CLONE_PROD_NS1_656.inscape.content  [RUN]
[0m11:18:59.347151 [debug] [Thread-1 (]: Acquiring new snowflake connection 'model.hmi_dbt_lib.content'
[0m11:18:59.348133 [debug] [Thread-1 (]: Began compiling node model.hmi_dbt_lib.content
[0m11:18:59.354156 [debug] [Thread-1 (]: Writing injected SQL for node "model.hmi_dbt_lib.content"
[0m11:18:59.355189 [debug] [Thread-1 (]: Began executing node model.hmi_dbt_lib.content
[0m11:18:59.411111 [info ] [Thread-1 (]: 1 of 1 START batch 2023-11-24 of HMI_CURATED_CLONE_PROD_NS1_656.inscape.content  [RUN]
[0m11:18:59.416974 [debug] [Thread-1 (]: Writing injected SQL for node "model.hmi_dbt_lib.content"
[0m11:18:59.451838 [debug] [Thread-1 (]: Using snowflake connection "model.hmi_dbt_lib.content"
[0m11:18:59.452831 [debug] [Thread-1 (]: On model.hmi_dbt_lib.content: /* {"app": "dbt", "dbt_version": "1.9.0b4", "profile_name": "hmi_dbt_lib", "target_name": "sso", "node_id": "model.hmi_dbt_lib.content"} */
create or replace temporary table HMI_CURATED_CLONE_PROD_NS1_656.inscape.content__dbt_tmp
         as
        (
with source as (
  select * from (select * from HMI_CURATED_CLONE_PROD_NS1_656.inscape.vw_content where content_recognition_start_timestamp >= '2023-11-24 00:00:00+00:00' and content_recognition_start_timestamp < '2023-11-25 00:00:00+00:00')
  
  limit 1000000
  
)
select
  hmi_uuid
  ,hashed_unique_tv_id
  ,zip_code
  ,dma
  ,content_tms_id as content_id
  ,content_title
  ,scheduled_content_start_time
  ,station_callsign
  ,content_start_media_time
  ,content_recognition_start_timestamp
  ,content_recognition_end_timestamp
  ,network
  ,live
  ,sha2(HMI_CURATED_CLONE_PROD_NS1_656.common.regexp_replace2(ip_address, '(\\b0+)(?!\\b)', ''), 256) as ip_address_hash
  ,input_category
  ,input_device
  ,app_service
  ,landed_timestamp
  ,created_timestamp
  ,modified_timestamp
  ,partition_date
from source
        );
[0m11:18:59.452831 [debug] [Thread-1 (]: Opening a new connection, currently in state init
[0m11:19:07.724147 [debug] [Thread-1 (]: SQL status: SUCCESS 1 in 8.272 seconds
[0m11:19:07.731156 [debug] [Thread-1 (]: Using snowflake connection "model.hmi_dbt_lib.content"
[0m11:19:07.732163 [debug] [Thread-1 (]: On model.hmi_dbt_lib.content: /* {"app": "dbt", "dbt_version": "1.9.0b4", "profile_name": "hmi_dbt_lib", "target_name": "sso", "node_id": "model.hmi_dbt_lib.content"} */
describe table HMI_CURATED_CLONE_PROD_NS1_656.inscape.content__dbt_tmp
[0m11:19:07.812949 [debug] [Thread-1 (]: SQL status: SUCCESS 21 in 0.080 seconds
[0m11:19:07.817650 [debug] [Thread-1 (]: Using snowflake connection "model.hmi_dbt_lib.content"
[0m11:19:07.817650 [debug] [Thread-1 (]: On model.hmi_dbt_lib.content: /* {"app": "dbt", "dbt_version": "1.9.0b4", "profile_name": "hmi_dbt_lib", "target_name": "sso", "node_id": "model.hmi_dbt_lib.content"} */
describe table HMI_CURATED_CLONE_PROD_NS1_656.inscape.content
[0m11:19:07.884428 [debug] [Thread-1 (]: SQL status: SUCCESS 21 in 0.066 seconds
[0m11:19:07.895469 [debug] [Thread-1 (]: Using snowflake connection "model.hmi_dbt_lib.content"
[0m11:19:07.895469 [debug] [Thread-1 (]: On model.hmi_dbt_lib.content: /* {"app": "dbt", "dbt_version": "1.9.0b4", "profile_name": "hmi_dbt_lib", "target_name": "sso", "node_id": "model.hmi_dbt_lib.content"} */
describe table HMI_CURATED_CLONE_PROD_NS1_656.inscape.content__dbt_tmp
[0m11:19:07.965229 [debug] [Thread-1 (]: SQL status: SUCCESS 21 in 0.069 seconds
[0m11:19:07.968238 [debug] [Thread-1 (]: Using snowflake connection "model.hmi_dbt_lib.content"
[0m11:19:07.969238 [debug] [Thread-1 (]: On model.hmi_dbt_lib.content: /* {"app": "dbt", "dbt_version": "1.9.0b4", "profile_name": "hmi_dbt_lib", "target_name": "sso", "node_id": "model.hmi_dbt_lib.content"} */
describe table "HMI_CURATED_CLONE_PROD_NS1_656"."INSCAPE"."CONTENT"
[0m11:19:08.035148 [debug] [Thread-1 (]: SQL status: SUCCESS 21 in 0.066 seconds
[0m11:19:08.043139 [debug] [Thread-1 (]: 
    In "HMI_CURATED_CLONE_PROD_NS1_656"."INSCAPE"."CONTENT":
        Schema changed: False
        Source columns not in target: []
        Target columns not in source: []
        New column types: []
  
[0m11:19:08.050146 [debug] [Thread-1 (]: Writing runtime sql for node "model.hmi_dbt_lib.content"
[0m11:19:08.051146 [debug] [Thread-1 (]: Using snowflake connection "model.hmi_dbt_lib.content"
[0m11:19:08.052139 [debug] [Thread-1 (]: On model.hmi_dbt_lib.content: /* {"app": "dbt", "dbt_version": "1.9.0b4", "profile_name": "hmi_dbt_lib", "target_name": "sso", "node_id": "model.hmi_dbt_lib.content"} */
delete from HMI_CURATED_CLONE_PROD_NS1_656.inscape.content DBT_INTERNAL_TARGET
    using HMI_CURATED_CLONE_PROD_NS1_656.inscape.content__dbt_tmp
    where (
    DBT_INTERNAL_TARGET.content_recognition_start_timestamp >= TIMESTAMP '2023-11-24 00:00:00+00:00'
    and DBT_INTERNAL_TARGET.content_recognition_start_timestamp < TIMESTAMP '2023-11-25 00:00:00+00:00'
    
    );
[0m11:19:40.732795 [debug] [Thread-1 (]: Snowflake adapter: Snowflake query id: 01b89c53-0712-4153-001a-6a831bd4980a
[0m11:19:40.732795 [debug] [Thread-1 (]: Snowflake adapter: Snowflake error: 000604 (57014): SQL execution canceled
[0m11:19:40.733801 [error] [Thread-1 (]: 1 of 1 ERROR creating batch 2023-11-24 of HMI_CURATED_CLONE_PROD_NS1_656.inscape.content  [[31mERROR[0m in 41.32s]
[0m11:19:40.734799 [error] [Thread-1 (]: Encountered an error while running operation: Database Error
  000604 (57014): SQL execution canceled
```

### Environment

```markdown
- OS: Windows 10 Enterprise
- Python: 3.12.7
- dbt: 1.9.0-b4
- dbt-snowflake: 1.9.0-b1
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

dbt cartesian join

### LINKED ISSUE #1256: [Bug] Microbatch timestamps incorrectly offset for system timezone in Snowflake
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Currently, microbatch timestamps are being recognized as `TIMESTAMP_NTZ` in Snowflake, instead of `TIMESTAMP_TZ`. As a result, if user's system timezone is in anything but UTC, Snowflake will offset the timezone, resulting in incorrect and duplicative rows loaded.

For example, if you ran a microbatch model with the `--event-end-time` of today (2024-11-05) it would produce the following code:
```
and [timestamp_field] < TIMESTAMP '2024-11-05 00:00:00+00:00'
```

When you look at this same timestamp in Snowflake you can see it's stored as `timestamp_ntz`:
image

When you convert this to a `timestamp_tz` then you'll see the system offset will takeover and adjust accordingly:
Screenshot 2024-11-05 at 1 15 05 PM

According to the docs, microbatch expects input data to be in UTC. Therefore, if your source column is of type `timestamp_tz` and in UTC, the two timestamps would be off by 8 hours in the above example - causing duplicative rows being inserted.

Instead of using the invalid `TIMESTAMP` function (which I believe is the cause for data being stored as UTC) - such as the below:
```
TIMESTAMP '2024-11-05 00:00:00+00:00'
```

dbt Core should instead use the `to_timestamp_tz` function that correctly stores this information as a `timestamp_tz` with the correct UTC offset and data type:
Screenshot 2024-11-05 at 1 25 05 PM

### Expected Behavior

Microbatch DDL statements should be operating off of `timestamp_tz` data types with a UTC offset of 0. Running a model with a microbatch materialization over and over again should not duplicate rows of data in the resulting dataset.

Insert/Delete statements should be operating off of the same datatype & UTC offset as source data.

### Steps To Reproduce

1. Connect dbt Cloud to a Snowflake project 
2. Ensure the Snowflake system timezone has a timezone offset broadly applied.
3. Create a source model with `event_time` configured on a `timestamp_tz` column in UTC.
4. Run the initial microbatch model from start to end (begins_on through now).
5. Re-run the microbatch model using a lookback of 1
6. Observe duplicate rows in the resulting data.

### Relevant log output

_No response_

### Environment

```markdown
- Python: 3.8.12
- dbt: dbt Cloud CLI - 0.38.21
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MichelleArk**
resolves https://github.com/dbt-labs/dbt-snowflake/issues/1256
resolved https://github.com/dbt-labs/dbt-adapters/issues/364

### Problem

When specifying a timestamp like `TIMESTAMP '2024-11-05 00:00:00+00:00'`, snowflake uses the system timezone, even if the timestamp has offsets. This causes issues in microbatch because the `delete` DDL statement is leveraging the `TIMESTAMP` typing, and is deleting the wrong records, potentially causing duplicate rows to be inserted.

### Solution

* explicitly use `to_timestamp_tz` when computing incremental predicates for microbatch DDL
* update tests to explicitly have timezone_tz input types to UTC (as we recommend for microbatch inputs)

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

File: dbt/include/snowflake/macros/materializations/merge.sql [hunk 1]
```diff
@@ -58,10 +58,10 @@
 
     {#-- Add additional incremental_predicates to filter for batch --#}
     {% if model.config.get("__dbt_internal_microbatch_event_time_start") -%}
-        {% do incremental_predicates.append("DBT_INTERNAL_TARGET." ~ model.config.event_time ~ " >= TIMESTAMP '" ~ model.config.__dbt_internal_microbatch_event_time_start ~ "'") %}
+        {% do incremental_predicates.append("DBT_INTERNAL_TARGET." ~ model.config.event_time ~ " >= to_timestamp_tz('" ~ model.config.__dbt_internal_microbatch_event_time_start ~ "')") %}
```
Comment (MichelleArk) [inline dbt/include/snowflake/macros/materializations/merge.sql:61]: Interestingly, just using the raw timestamp (that includes UTC offset, which `model.config.__dbt_internal_microbatch_event_time_start` does) works well. E.g. just removing `TIMESTAMP` would have been enough here. However, the `to_timestamp_tz` piece for more intentional so I've opted for that.

Comment (QMalcolm) [reply dbt/include/snowflake/macros/materializations/merge.sql:61]: I like how using `TIMESTAMP` was causing the issue 🫠 I like th emove to using `to_timestamp_tz` instead of just removing `TIMESTAMP` 👍

**Review by QMalcolm — APPROVED** [review]
:shipit: You are crushiiiing it

**Review by adrianburusdbt — APPROVED** [review]

**Comment by MichelleArk** [comment]
New commit https://github.com/dbt-labs/dbt-snowflake/pull/1257/commits/238bae2809283186e37eb7a20c3d76c519d06169 just cleans up some extraneous configuration in test code, that was accidentally left in from development. No functional changes.
