### PR TITLE
Speedup catalog string comparison by using ilike before equals

### LINKED ISSUE #1035: [Bug] `snowflake__get_catalog_schemas_where_clause_sql` is very slow
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

`dbt docs generate` for a single model takes 30-90s

### Expected Behavior

`dbt docs generate` for a single model takes 3-4s

### Steps To Reproduce

1. Run `dbt docs generate` for a single model

### Relevant log output

_No response_

### Environment

```markdown
- OS: MacOS
- Python: 3.12
- dbt-core: 1.8
- dbt-snowflake: 1.8
```

### Additional Context

Ad-hoc internal testing caused query time to drop from 30-90s to 3-4s.

### PR DESCRIPTION
**Pull request by aranke**
resolves #1035

### Problem

`dbt docs generate` for a single model takes 30-90s

### Solution

Speed up `information_schema` comparison using `ilike` to drop performance down to 3-4s.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

File: dbt/include/snowflake/macros/catalog.sql [hunk 1]
```diff
@@ -95,9 +95,14 @@
...
 
+{% macro snowflake__catalog_equals(field, value) %}
+    "{{ field }}" ilike '{{ value }}' and upper("{{ field }}") = upper('{{ value }}')
+{% endmacro %}
+
+
 {% macro snowflake__get_catalog_schemas_where_clause_sql(schemas) -%}
     where ({%- for schema in schemas -%}
-        upper("table_schema") = upper('{{ schema }}'){%- if not loop.last %} or {% endif -%}
+        {{ snowflake__catalog_equals('table_schema', schema) }}{%- if not loop.last %} or {% endif -%}
```
Comment (mikealfare) [inline dbt/include/snowflake/macros/catalog.sql:105]: You need a close parenthesis after the function call (`...schema) }}){%-...`)

File: .changes/unreleased/Under the Hood-20240425-144556.yaml [hunk 2]
```diff
@@ -0,0 +1,6 @@
+kind: Under the Hood
+body: Speedup catalog string comparison by using ilike before equals
+time: 2024-04-25T14:45:56.549787+02:00
+custom:
+  Author: aranke
+  Issue: ' '
```
Comment (colin-rogers-dbt) [inline .changes/unreleased/Under the Hood-20240425-144556.yaml:6]:
```suggestion
  Issue: '982'
```
